### PR TITLE
make reader work for python3

### PR DESCRIPTION
**Pull request by cg-laser**
I tested this on snowflake. I can read in the data with python3. It doesn't crash but I did not verify that the data is valid.

### CODE REVIEW

**Comment by anelles** [comment]
@cg-laser can you test whether snowshovel compiles on mac with ROOT 6? I would rather not break my installation if we haven't fixed this yet. I am happy to then also test data consistency when switching over.

**Comment by cg-laser** [comment]
I didn't try it yet on my mac... I'll try to test this soon. 
You can always install snowshovel with root 6 next to the current installation.  (I didn't commit the snowshovel fixes yet. I had problems with the svn yesterday)

**Comment by cg-laser** [comment]
I managed to compile everything on my mac, but it required a little bit of hacking. I guess mostly because python3 is not the default python version on my system. I wrote up detailed install instructions:

For python3.7
——————————————
wget https://root.cern/download/root_v6.18.00.source.tar.gz
tar -zxf root_v6.18.00.source.tar.gz
cd root-6.18.00/
mkdir source
mv * source/
mkdir build
cd build/

cmake ../source/ -DPYTHON_EXECUTABLE=/usr/local/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Headers -DPYTHON_LIBRARY=/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib

cmake --build . -- -j4

export PYTHONPATH=“”
source bin/thisroot.sh

# install snowshovel
————————————
# change the following TAM files manually

Performing status on external item at 'tam':
M       tam/inc/TAMBranchInfo.h
M       tam/inc/TAMSelector.h
hep-dhcp199:trunk cglaser$ svn diff .
hep-dhcp199:trunk cglaser$ svn diff tam
Index: tam/inc/TAMBranchInfo.h
===================================================================
--- tam/inc/TAMBranchInfo.h	(revision 24)
+++ tam/inc/TAMBranchInfo.h	(working copy)
@@ -11,6 +11,7 @@


 #include <typeinfo>
+using std::type_info;


 #ifndef ROOT_TNamed
Index: tam/inc/TAMSelector.h
===================================================================
--- tam/inc/TAMSelector.h	(revision 24)
+++ tam/inc/TAMSelector.h	(working copy)
@@ -35,6 +35,8 @@
 class TAModule;
 class TAMOutput;
 class TBranchRef;
+class TProcessID;
+class TRefTable;

 class TAMSelector : public TSelector {
 protected:


export SNS=/Users/cglaser/software/snowShovel/trunk_root6/trunk
export LD_LIBRARY_PATH=${SNS}/lib:${LD_LIBRARY_PATH}
# add library path explicitly to env variable:
export DYLD_LIBRARY_PATH=${SNS}/lib:/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/:${DYLD_LIBRARY_PATH}
export PYTHONPATH=${SNS}/lib:${PYTHONPATH}

# getting snowshovel compiled with python3 requires some hacks because python3 is not the default version on my system
# create symlinks to python3 to make python3 the default version in this shell
ln -s /usr/local/bin/python3-config python-config
ln -s /usr/local/bin/python3 python
addbin $(pwd) # add folder where you placed the symlinks to your PATH environment variable

./configure
make

#this leads to a lining error which can be manually fixed by providing the path to the library (-L option)
g++ -g -O2 -dynamiclib -single_module -undefined dynamic_lookup -install_name /Users/cglaser/software/snowShovel/trunk_root6/trunk/lib/libtam.so -g -bind_at_load -o lib/libtam.so tam/TAMBranchInfo.o tam/TAMObjBranchLoader.o tam/TAMObjLoader.o tam/TAMOutput.o tam/TAMPythonModBase.o tam/TAMSelector.o tam/TAMTreeBranchLoader.o tam/TAMTreeLoader.o tam/TAMVirtualBranchLoader.o tam/TAMVirtualLoader.o tam/TAModule.o tam/G__tam.o -lpython3.7m -ldl -framework CoreFoundation -L/Users/cglaser/software/root-6.18.00/build/lib -L/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/ -lGui -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -lpthread -stdlib=libc++ -lm -ldl

#then execute make again
make

# now set the ROOT_INCLUDE_PATH to the snowshovel and root include directories
export ROOT_INCLUDE_PATH=${SNS}/include:/home/arianna/software/root-6.18.00/build/include/

**Comment by christophwelling** [comment]
On Ubuntu:

The line 

`g++ -g -O2 -dynamiclib -single_module -undefined dynamic_lookup -install_name /Users/cglaser/software/snowShovel/trunk_root6/trunk/lib/libtam.so -g -bind_at_load -o lib/libtam.so tam/TAMBranchInfo.o tam/TAMObjBranchLoader.o tam/TAMObjLoader.o tam/TAMOutput.o tam/TAMPythonModBase.o tam/TAMSelector.o tam/TAMTreeBranchLoader.o tam/TAMTreeLoader.o tam/TAMVirtualBranchLoader.o tam/TAMVirtualLoader.o tam/TAModule.o tam/G__tam.o -lpython3.7m -ldl -framework CoreFoundation -L/Users/cglaser/software/root-6.18.00/build/lib -L/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/ -lGui -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -lpthread -stdlib=libc++ -lm -ldl`

is not necessary (and won't work anyway).

Also, the line
`export LD_LIBRARY_PATH=${SNS}/lib:${LD_LIBRARY_PATH}`
should be changed to 
`export LD_LIBRARY_PATH=${SNS}/lib:${SNS}:${LD_LIBRARY_PATH}`
($SNS also needs to be in the library path.)

**Comment by anelles** [comment]
Does this mean that this now works on your system (and the cluster)? That would be very nice!

**Comment by christophwelling** [comment]
I haven't tried it on the cluster, but it seems to work on my PC.

**Comment by cg-laser** [comment]
@christophwelling can you also test it on the cluster and then approve this pull request?

**Comment by cg-laser** [comment]
it should be p2/3 compatible, so I would merge it already now (after the cluster test)

**Pull request merged**
