### PR TITLE
hl-trigger coincidence window

### PR DESCRIPTION
**Pull request by cg-laser**
changes hl trigger to count coincidence window from point of threshold crossing only and not from all points above threshold

This seems to be closer to how the hardware works.

### CODE REVIEW

**Comment by anelles** [comment]
Pull looks good, but it probably needs an update from the master to make the tests pass again.

**Review by anelles — APPROVED** [review]
Sorry that became dormant. Looks still good.

**Comment by anelles** [comment]
@cg-laser, merge?

**Comment by cg-laser** [comment]
this will break all tests... I think it would be better to make a new hl trigger module with this change.

**Pull request closed without merging**
