### PR TITLE
Sphinx fix

### PR DESCRIPTION
**Pull request by christophwelling**
Updates the sphinx documentation and makes it a little prettier.
I chose the "Read The Docs" theme, which requires pip install sphinx_rtd_theme, but I think the added features are worth it.

### CODE REVIEW

**Comment by christophwelling** [comment]
Apparently you can also make the documentation show up on github: https://www.docslikecode.com/articles/github-pages-python-sphinx/
Should we do this? Looks like that would require including all the html files in the repository.

**Comment by anelles** [comment]
> Apparently you can also make the documentation show up on github: https://www.docslikecode.com/articles/github-pages-python-sphinx/
> Should we do this? Looks like that would require including all the html files in the repository.

In principle, yes please! 
You can have a look at how @bhokansonfasig did it for pyrex, https://bhokansonfasig.github.io/pyrex/build/html/index.html, he may also be able to answer some detailed questions, if he remembers ;)

**Comment by anelles** [comment]
@christophwelling do you want to do the github website later or in this commit? 
Also, thanks for looking into this, can you maybe add a littel how-to somewhere (probably on the wiki) to make sure that the next person to update this, does not have to reinvent the wheel?

**Comment by cg-laser** [comment]
I also found this tutorial a while ago: https://daler.github.io/sphinxdoc-test/includeme.html
It uses a separate repo to store all the html, but I'm not sure if this is the best way to go. 

And yes, we should host it on github pages.

**Comment by christophwelling** [comment]
I went with the tutorial Christian posted, and that works pretty well. I think pushing all the documentation onto a specific branch is a pretty good solution. That makes it easy to update it without spamming the main repository.

**Comment by anelles** [comment]
Cool, this looks really nice. 
And also now one can easily see that we need tons of additional code documentation ... 
Is the workflow now that this updates itself? I see the deployment tab now in the pull requests.

**Comment by christophwelling** [comment]
Yes, this has to be deployed by hand, but if everyone adds new modules to the docs and writes good docstrings, this is not much work. You just need to rerun make html and push the new files to the gh-pages branch

**Comment by anelles** [comment]
@cg-laser, @christophwelling  the website of course still needs the logo for NuRadio that we showed among others at the ICRC.

**Comment by christophwelling** [comment]
No problem. If @cg-laser sends it to me, I can add it.

**Comment by cg-laser** [comment]
what is the website to access the documentation?

**Comment by anelles** [comment]
It says on the wiki https://nu-radio.github.io/NuRadioReco/
We should probably place this more prominently. I have started working on missing doc-strings.

**Comment by christophwelling** [comment]
The pull request puts that in the readme as well

**Comment by christophwelling** [comment]
The documentation now has a logo as well. If there are no further suggestions I think we can merge

**Comment by cg-laser** [comment]
do we have a 'documentation for dummies' on how to regenerate the documentation?

**Comment by christophwelling** [comment]
Yes, on the Wiki

**Comment by cg-laser** [comment]
I see that you updated https://github.com/nu-radio/NuRadioReco/wiki/Documentation, can you also add a simple "todo" what commands I would need to execute to update the documentation 
1) if I changed a doc string)
2) if I added a new function to an existing class
3) if I added a new module/class/file

**Comment by cg-laser** [comment]
@christophwelling what about my request above? We should not just ignore comments and merge pull requests.

**Comment by christophwelling** [comment]
These ToDos are on the Wiki now. And the Wiki is not really part of a pull request, so it looked like this was complete to me.

**Comment by cg-laser** [comment]
thanks

**Pull request merged**
