### PR TITLE
RNO phased array

### PR DESCRIPTION
**Pull request by daniel-zid**
The PhasedArray branch was too old, so I created this copy with the new files. This branch contains the phased array trigger with an updated configuration. There are some examples in the NuRadioReco/examples/PhasedArray/ folder than can be used as a basis for a more complete study of the phased array.

### CODE REVIEW

**Comment by daniel-zid** [comment]
I've updated the code with some documentation and changed the event generator for the effective volume example. Please tell me if the documentation is not clear and I'll modify it. The examples should work immediately with a complete NuRadioReco and NuRadioMC installation.

**Comment by daniel-zid** [comment]
The noise_trigger_rate.py is actually quite important, as it allows to
study the noise
trigger rate and therefore the correct threshold. I don't mind moving it to
the examples
folder.

The results are just a sample of what one can expect for the SNR curves if
properly
executed. I can remove it.

**Comment by anelles** [comment]
I also thought that the results were too much, but they are tiny and I have to say that I found them helpful. These examples need quite heavy lifting for the simulations so having some results to see what they will look like sounds good to me.

**Comment by daniel-zid** [comment]
Ooops, I've just removed them.

**Comment by daniel-zid** [comment]
Aaaand, they're back.

**Pull request merged**
