### PR TITLE
Adds function to get the amp response directly from the detector class

### PR DESCRIPTION
**Pull request by christophwelling**
It's annoying to always use the analog_components modules manually every time you need the amp response. This PR simplifies things

### CODE REVIEW

**Review by cg-laser — CHANGES_REQUESTED** [review]
yes this is super useful. 

For sake of modularity, shouldn't the `analog_components` return a list of amplifiers they implement? 
Also this is not save for possible name clashes. This would be solved by giving the function an additional parameter "experiment" or so which would be "ARIANNA" or "RNO_G". Or a list of experiments. The default could be `["RNO_G", "ARIANNA"]` for now.

**Comment by christophwelling** [comment]
Having a list of amps in the analog components is a good idea, I will add that.
I'm not sure about having the experiment as a parameter. The detector class itself should have all the information it needs to find the right amplifier. Otherwise this is can easily cause issues if we want to use it inside modules, where we can't easily change how this is called from the outside.
Could somehow add the name of the experiment to the detector description?

**Comment by christophwelling** [comment]
I changed it so we get the amp names from the analog_components file now. It now also raises an error if the amp name is not unique

**Review by cg-laser — APPROVED** [review]
looks good. 

There is one thing though that is not supported. For ARIANNA we already have individual amp measurements available that can be requested via `get_amplifier_response` if an individual. amp is specified. However, we need think through how to properly implement amp measurements for all detectors at some point. This will be too much for this PR

**Pull request merged**
