### PR TITLE
SimChannels for cosmic ray events

### PR DESCRIPTION
**Pull request by christophwelling**
Makes the efieldToVoltageConverterPerEfield consider signal travel times between channels for cosmic ray events, so simChannels can be used for CR as well

### CODE REVIEW

**Review by cg-laser — CHANGES_REQUESTED** [review]
Can you add comments into the code that explains why you need to do that for cosmic rays?

The logic only works if the antennas have the depth. It might be useful to implement better time delay calculation here (?). At least, can you add a comment that this is assumed?

**Comment by christophwelling** [comment]
I don't understand what you mean. This is the exact same thing as in the efieldToVoltageConverter.

**Comment by cg-laser** [comment]
Yes I know. The functionality is also limited in that module. For ARIANNA, all antennas are at the same depth, so it does not matter. But for other configurations it might matter. 
I'm not saying that we need to implement it in this PR, but it will be helpful to mention that limitation in a comment in the code. 
I would also mention, that for cosmic rays, we simulate just one efield for each station

**Comment by christophwelling** [comment]
Ah, I didn't consider the different index of refraction between air and ice. I added a comment explaining this

**Review by cg-laser — APPROVED** [review]
thanks Christoph

**Pull request merged**
