### PR TITLE
MONGODB_URL, Dockerfile

### PR DESCRIPTION
**Pull request by shallmann**
-MongoDB uses MONGODB_URL if set, otherwise it defaults to previous implementation
- added Dockerfile needed for deployment at DESY

### CODE REVIEW

**Review by cg-laser — COMMENTED** [review]
can you add a readme file of how to start the docker container?

**Comment by cg-laser** [comment]
just a quick comment: Executing the index.py file to start the server is only for debug purposes. The production server should be started with `guincorn`

**Comment by cg-laser** [comment]
I thought you could just add a README file in this subdirectory with the instructions how to run it. Then the information is easy to find

**Comment by shallmann** [comment]
done

as in the instructions it is not in a subdirectory though... better move Dockerfile/readme to e.g.  NuRadioReco/detector/webinterface ?

**Comment by shallmann** [comment]
Good news! After discussions with Philipp on Friday, we are now able to deploy ourselves via jenkins. Currently this branch is used in deployment, and with the latest change, I verified:
- I can build a local container, sshuttle into desy and enter data there
- I deployed this branch and the container is already running at http://radio-test.zeuthen.desy.de (I successfully entered data)

See attached screenshots.
screenshot 2021-01-24 at 03 06 21
screenshot 2021-01-24 at 02 47 30

Should we merge?

**Review by cg-laser — APPROVED** [review]
awesome, that is great. Then I guess I can continue with implementing additional features. But this should be on a different PR. Green light from me for merging

**Pull request merged**
