### PR TITLE
fix ARIANNA-200 detector description

### PR DESCRIPTION
**Pull request by cg-laser**
fix global position (to be usable in NuRadioMC) and change commissiontime to 2017 (as default simulate date in NuRadioMC is 2018)

### CODE REVIEW

**Comment by anelles** [comment]
Sorry, just merged the master in, but did it in a strange way.

**Comment by christophwelling** [comment]
I was wondering why I got an email that the tests work now :-)

**Comment by cg-laser** [comment]
why are there so many changes wrt to the master?

**Comment by anelles** [comment]
@lpyras the official procedure is that you should merge this now.

**Comment by cg-laser** [comment]
actually I created the PR but I'm confused why there are so many additional changes to the master

**Comment by anelles** [comment]
It might have been my fault in merging the master in a strange way. I think you need to merge the master again and then it should be fine.

**Pull request merged**
